INSERT INTO fähigkeit VALUES (1,'DB_Admin')
INSERT INTO fähigkeit VALUES (2,'MS_Admin')
INSERT INTO fähigkeit VALUES (3,'LX_Admin')
INSERT INTO fähigkeit VALUES (4,'AX_Admin')
INSERT INTO fähigkeit VALUES (5,'SR_Admin')
