CREATE TABLE Kind (
  KVNAME VARCHAR(45) NOT NULL,
  KGEBDAT DATE NOT NULL,
  KGESCHL VARCHAR(1) NOT NULL,
  PNR INT NOT NULL,
  PRIMARY KEY (KVNAME, PNR),
  FOREIGN KEY (PNR) REFERENCES Mitarbeiter (PNR)
);