CREATE TABLE Stelle (
  STNR VARCHAR(5) NOT NULL,
  STBEZ VARCHAR(35) NOT NULL,
  PNR INT NOT NULL,
  KSTNR VARCHAR(4) NOT NULL,
  TAETNR INT NOT NULL,
  PRIMARY KEY (STNR),
  FOREIGN KEY (KSTNR) REFERENCES Kostenstelle(KSTNR),
  FOREIGN KEY (TAETNR) REFERENCES Tätigkeit(TAETNR)
);