CREATE TABLE stellfae (
	stnr VARCHAR(5) NOT NULL,
	faehnr INTEGER NOT NULL,
	fgrads VARCHAR(1) NOT NULL,
	PRIMARY KEY (stnr, faehnr),
	FOREIGN KEY (stnr) REFERENCES stelle ON DELETE CASCADE ON UPDATE NO ACTION,
	FOREIGN KEY (faehnr) REFERENCES fähigkeit ON DELETE CASCADE ON UPDATE NO ACTION
)
	
