CREATE TABLE taetfae (
	taetnr INTEGER NOT NULL,
	faehnr INTEGER NOT NULL,
	fgradt VARCHAR(30),
	PRIMARY KEY (taetnr, faehnr),
	FOREIGN KEY (taetnr) REFERENCES tätigkeit ON DELETE CASCADE ON UPDATE NO ACTION,
	FOREIGN KEY (faehnr) REFERENCES fähigkeit ON DELETE CASCADE ON UPDATE NO ACTION
)
	
